### ISSUE TITLE
MINOR: Have music play from its last position when a user exits and retries

### ISSUE THREAD

**Issue by Chocolate-Chip-Computing** [Chocolate-Chip-Computing/DebianNewbieScript#18]
Have the music resume at its last position if the user is forced to retry the script for whatever reason

**Comment by Faalentijn** [comment]
add the --save-position-on-quit option to mpv. It will store the current time stamp so it starts at the same point if you try to watch it again.

Also do not install things outside of the repos. That is a very big no no, especially when the software is just in the repo.

**Comment by Chocolate-Chip-Computing** [comment]
Thanks. I was told that the downloading of Youtube-dl through the site was better than the download through apt due to youtube-dl being updated every few weeks. The apt version is often months behind and breaks frequently. I'll consider re-adding the apt version, but right now I think this version is ok.
